name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: run the checkout action
        uses: actions/checkout@v1
      - name: list all changed files
        shell: bash
        run: |
            files=$(git diff --name-only origin/$GITHUB_BASE_REF...${{ github.sha }})
            IFS=$'\n'; files=($files); unset IFS;
            file --mime "${files[@]}"
      - name: list all changed files with the wrong encoding
        shell: bash
        run: |
            files=$(git diff --name-only origin/$GITHUB_BASE_REF...${{ github.sha }})
            IFS=$'\n'; files=($files); unset IFS;
            ! file --mime "${files[@]}" | grep -v "charset=utf-8\|charset=utf-16be\| (No such file or directory)$"
